services:

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"  # Expose Redis for local dev
    volumes:
      - redis-data:/data

  frontend:
    build:
      context: ./better-reads/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./better-reads/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./better-reads/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./better-reads/backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://rex015:iDPU4rvt5HjtDrW1@sandbox.bcebozm.mongodb.net/bookdb?retryWrites=true&w=majority&appName=Sandbox
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongodb
      - redis

  recommender:
    build: ./recommender
    container_name: fastapi-recommender
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  redis-data:
